#!/usr/bin/env bash
# A script that displays information about domain

domain_sub_info () {
	command=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $command" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
	# if only one argument
	domain_sub_info "$1" "www"
	domain_sub_info "$1" "lb-01"
	domain_sub_info "$1" "web-01"
	domain_sub_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	# if two argument
	domain_sub_info "$1" "$2"
fi
