#!/usr/bin/env bash
# A script that transfers a file from a client to server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

File_src="$1"
IP="$2"
User="$3"
P_key="$4"

scp -o StrictHostKeyChecking=no -i "$P_key" "$File_src" "${User}@${IP}:~/"
