#!/usr/bin/env bash
#A script that installs nginx

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service start nginx
