#!/usr/bin/env bash
#A script that installs nginx

config_content="listen 80;\nroot /var/www/html/;\nindex index.html;\nlocation / {\n $uri $uri/ =301;\n}"

sudo apt-get update
sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/html/index.html
sudo chmod 0755 /var/www/html/index.html

sudo sed -i "s/listen 80 default_server;/${config_content}/" /etc/nginx/sites-available/default
sudo service start nginx
