#!/usr/bin/env bash
# A script that configures Nginx server to return
# a header 'X-Served-By'

if ! command -v nginx &> /dev/null; then
   sudo apt-get update
   sudo apt-get install nginx -y
fi

static_html_dir="/var/www/static_html"
if [ ! -d "$static_html_dir" ]; then
	sudo mkdir -p "$static_html_dir"
fi

static_html="$static_html_dir/index.html"
echo "Hello Everyone" | sudo tee "$static_html" > /dev/null

error_html="$static_html_dir/404.html"
if [ ! -f "$error_html" ]; then
	touch "$error_html"
	echo -e "C'est ne pas une page" | sudo tee "$error_html" > /dev/null
fi

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root $static_html_dir;
	index index.html index.htm;
	add_header X-Served-By \$HOSTNAME;
	
	error_page 404 /404.html;
	location = /404.html {
		root $static_html_dir;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
