#!/usr/bin/env bash
# A script that installs and configures a Load Balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

echo 'ENABLED=1' >> sudo tee /etc/default/haproxy

sudo mv /etc/haproxy/haproxy.cfg{,.original}

# echo 'frontend http
#              bind *:80
#              mode http
#              default_backend web_backend' >> sudo tee /etc/haproxy/haproxy.cfg

echo 'frontend http
               bind *:80
               mode http
               default_backend web_backend

backend web_backend
              balance roundrobin
              mode http
              server 351953-web-01 ubuntu@54.237.100.5
              server 351953-web-02 ubuntu@52.3.255.219' | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start
