#!/usr/bin/env bash
# A script that configures nginx port to 80
sed -i 's|listen 8080 default_server;|listen 80 default_server;|' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
