#!/usr/bin/env bash
# A script that configures nginx port to 80
sed -i '0,/8080/s//80/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx stop
