#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration,
#displays Best School and then Hi on a new line.

n=0
while [ $n -le 9 ]
do
	echo "Best School"
	if [ $n -eq 8 ]; then
		echo "Hi"
	fi
	((n += 1))
done
