#!/usr/bin/env bash
# displays numbers from 1 to 20 and:...

n=1
while [ $n -le 20 ]
do
	echo "$n"
	if [ $n -eq 4 ]; then
		echo "bad luck from China"
	elif [ $n -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $n -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((n++))
done
