#!/usr/bin/env bash
# gives you information about the school file.

var="school"
if [ -e $var ]; then
	echo "school file exists"
else
	echo "school file does not exists"
fi
if [ -s $var ]; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f $var ]; then
	echo "school is a regular file"
fi
