#!/usr/bin/env bash
#Changes the IP address from arbitrary correct one
#makes a backup copy of /etc/hosts
cp /etc/hosts ~/hosts.backup
sed -i 's/^127.*$/127.0.0.2	localhost/' ~/hosts.backup
echo "8.8.8.8	facebook.com" >> ~/hosts.backup
cp ~/hosts.backup /etc/hosts
rm ~/hosts.backup
