#!/usr/bin/env bash
# A script that runs who am i on the user passed as argument

User="$1"

if [ $# -lt 1 ]; then
	echo "Usage: $0 username"
	exit 1
fi

if id "$User" &> /dev/null; then
	sudo -u "$User" whoami
fi
